### ISSUE TITLE
Config.json not loading for html file.

### ISSUE THREAD

**Issue by killmast** [Loqrin/FiveM-Material_Load-Loading-Screen#2]
Here's the error I keep getting when viewing the project in chrome's src viewer:
[https://pastebin.com/2TxcfmFk](https://pastebin.com/2TxcfmFk)

The background image, music and text (everything in the Config.json) will not load due to that javascript error I'm getting. Even when I load it on the server it does the same thing.

**Comment by Loqrin** [comment]
You can't open the index.html in a web browser while using the protocol file://.
Test it in-game instead of in your web browser, or alternatively setup a web server on your local PC (there's plenty of tutorials on YouTube)
