### ISSUE TITLE
Doesn't load YT Audio

### ISSUE THREAD

**Issue by rdephillip** [Loqrin/FiveM-Material_Load-Loading-Screen#4]
The only YT ID I've found that works is the one you have provided in the default config.json .  Any insights on what can be done to resolve this?

**Comment by InfernalPlank** [comment]
Same issue here.

**Comment by mifsopo** [comment]
you must download the youtube song as a .ogg and then rename it as the current one or go into the __resource.ua and add   
    'LoadingScreen/audio/(song).ogg', @RHQ-Rusty @rdephillip

**Comment by rdephillip** [comment]
The latest version doesn't use OGG file format @mifsopo it pulls directly from YouTube.  In fact, if you TAB enough in your loading screen you can see the video playing just off the standard visible area.  The issue appears to be that, for some reason, the mod doesn't properly load other videos.

I have reported it, but it is incredibly low on my own dev teams list as to look into the code and see what is causing any issues.  It could be the limited to a chromium in client browser issue.  I am giving the dev a chance to look at his own code and address it. I will be looking at his code as soon as it bubbles up on my list and if I can fix it I will submit it to them as an update or a fork.

**Comment by InfernalPlank** [comment]
Any update @rdephillip ?

**Comment by rdephillip** [comment]
Nothing yet, It's so low on our server's priorities since so many ESX Mods are broken.

**Comment by codibez** [comment]
Has this been addressed yet? I am still getting this issue.

**Comment by rdephillip** [comment]
As far as I am aware it is still happening. I am no longer maintaining a server for a community so I am not putting any of my time into working on this. I ended up using the default music myself because nothing else would work.

**Comment by OfficialRDB** [comment]
Well v1.0 still works the best for me only the sound stops after a few seconds.

**Comment by rdephillip** [comment]
I have moved on from managing an RP server and do not wish to receive messages from here any longer.
