### ISSUE TITLE
my Background Image doesnt load - the screen stays dark grey on connecting

### ISSUE THREAD

**Issue by Valkyrionas** [Loqrin/FiveM-Material_Load-Loading-Screen#9]
Hello, 

I recently have the problem, that the background image won't load... so it stays default on that dark grey nearly black colour, otherwise all other things besides the music workaround in the issues found here works great... maybe anyone can say which parameters i need to enable/disable to get the image work properly ? I used a own shot photo .jpg with 1920x1080..

i got tested with usebackgroundcolour = true / false
backgroundcolour = 20,20,20 or 0,0,0 (doesnt seem to have an effect)
usetextcolour = "false" 
textcolour ="0,0,0"
boldtext = true
servertitle = "insertanytitlehere"
YTvideoid= "",
"videovolume" : ""  (im using the workaround with an own mp3.file)

the rules/servers and content 1-7 doesnt have an effekt and are shown properly as configured

both, music and backgroundimage are located in the folder of the index.html in folders with the names "music" and "image" and are written in the __resource.lua

thanks for reading and in advance for any helpful comments ;)

**Comment by lawlietgod** [comment]
In css folder edit style.css 
Add this: background-image: url("A LINK TO YOUR IMAGE, UPLOAD TO IMGUR");

And then try to restart it...
